name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [main]

jobs:
  production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest
      
      - name: Pull Production Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Biome check
        run: pnpm check
      
      - name: Build project
        run: pnpm build
      
      - name: Build (Production)
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy Production
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
